    export const games = [
  {
    id: '1',
    homeTeam: 'מכבי תל אביב',
    awayTeam: 'הפועל ירושלים',
    time: '19:30',
    date: '2025-07-15',
    location: 'ספורטק',
    medics: 4,
  },
  {
    id: '2',
    homeTeam: 'הפועל חיפה',
    awayTeam: 'בית"ר ירושלים',
    time: '20:00',
    date: '2025-07-16',
    location: 'סטדיון דוחא',
    medics: 2,
  },
  {
    id: '3',
    homeTeam: 'בני יהודה',
    awayTeam: 'מכבי חיפה',
    time: '18:00',
    date: '2025-07-17',
    location: 'איצטדיון טדי',
    medics: 3,
  },
  {
    id: '4',
    homeTeam: 'הפועל תל אביב',
    awayTeam: 'הפועל באר שבע',
    time: '21:00',
    date: '2025-07-18',
    location: 'אצטדיון בלומפילד',
    medics: 5,
  },

];


export const categories = [
  {
    id: '1',
    name: 'כדורגל',
    image: 'https://example.com/football.jpg',
    description: 'משחקי ליגת העל בכדורגל',
    games: [
  {
    id: '1',
    homeTeam: 'מכבי תל אביב',
    awayTeam: 'הפועל ירושלים',
    time: '19:30',
    date: '2025-07-15',
    location: 'ספורטק',
    medics: 4,
  },
  {
    id: '2',
    homeTeam: 'הפועל חיפה',
    awayTeam: 'בית"ר ירושלים',
    time: '20:00',
    date: '2025-07-16',
    location: 'סטדיון דוחא',
    medics: 2,
  },
  {
    id: '3',
    homeTeam: 'בני יהודה',
    awayTeam: 'מכבי חיפה',
    time: '18:00',
    date: '2025-07-17',
    location: 'איצטדיון טדי',
    medics: 3,
  },
  {
    id: '4',
    homeTeam: 'הפועל תל אביב',
    awayTeam: 'הפועל באר שבע',
    time: '21:00',
    date: '2025-07-18',
    location: 'אצטדיון בלומפילד',
    medics: 5,
  },
  {
    id: '5',
    homeTeam: 'מכבי נתניה',
    awayTeam: 'סקציה נס ציונה',
    time: '19:45',
    date: '2025-07-19',
    location: 'איצטדיון נתניה',
    medics: 2,
  },
  {
    id: '6',
    homeTeam: 'מכבי פתח תקווה',
    awayTeam: 'הפועל כפר סבא',
    time: '20:30',
    date: '2025-07-20',
    location: 'אצטדיון המושבה',
    medics: 3,
  },
  {
    id: '7',
    homeTeam: 'הפועל רעננה',
    awayTeam: 'הפועל רמת גן',
    time: '18:30',
    date: '2025-07-21',
    location: 'איצטדיון רעננה',
    medics: 1,
  },
  {
    id: '8',
    homeTeam: 'מכבי יבנה',
    awayTeam: 'הפועל אשדוד',
    time: '19:00',
    date: '2025-07-22',
    location: 'אצטדיון היובל',
    medics: 2,
  },
  {
    id: '9',
    homeTeam: 'הפועל באר שבע',
    awayTeam: 'בית"ר ירושלים',
    time: '20:15',
    date: '2025-07-23',
    location: 'אצטדיון טוטו טרנר',
    medics: 4,
  },
  {
    id: '10',
    homeTeam: 'מכבי תל אביב',
    awayTeam: 'הפועל רמת השרון',
    time: '19:00',
    date: '2025-07-24',
    location: 'ספורטק',
    medics: 3,
  },
  {
    id: '11',
    homeTeam: 'הפועל חיפה',
    awayTeam: 'מכבי פתח תקווה',
    time: '21:00',
    date: '2025-07-25',
    location: 'אצטדיון קרית חיים',
    medics: 2,
  },
  {
    id: '12',
    homeTeam: 'בני סכנין',
    awayTeam: 'הפועל תל אביב',
    time: '20:00',
    date: '2025-07-26',
    location: 'אצטדיון דוחא',
    medics: 3,
  },
],
  },
  {
    id: '2',
    name: 'כדורסל',
    image: 'https://example.com/basketball.jpg',
    description: 'ליגת ווינר בכדורסל',
    games: [
      // ...משחקים של כדורסל
    ],
  },
  {
    id: '3',
    name: 'פינג פונג',
    image: 'https://example.com/pingpong.jpg',
    description: 'טורנירי שולחן',
    games: [
      // ...משחקים של פינג פונג
    ],
  },

    {
    id: '4',
    name: ' טניס',
    image: 'https://example.com/pingpong.jpg',
    description: 'טורנירי שולחן',
    games: [
      // ...משחקים של פינג פונג
    ],
  },
];
